// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path="./.sst/platform/config.d.ts" />


// TODO: drop eslint config from old nextjs boilerplate
// TODO: better password creation/DATABASE_URL etc secret creation (e.g. from env var, or autogenerated, or from sst secret)
// TODO: separate service for dashboard? would require a dependency on first service which runs setup-config becoming stable, probably would need `wait: true` on that.
// TODO: is SERVER_URL working? seems so.
// TODO: put migrate/setup-config in their own service which gets conditionally deployed to avoid redeployment error on tenant pkey?
// TODO: hatchet-worker in same vpc
// TODO: get it working when no route53 domain provided (bastion helpful here)
// TODO: add tagging to all raw pulumi/non-sst resources


export default $config({
  app(input) {
    return {
      name: "hatchet",
      removal: input?.stage === "production" ? "retain" : "remove",
      protect: ["production"].includes(input?.stage),
      home: "aws",
    };
  },
  async run() {
    const infra = await import("./infra/main")

    return {
      Bastion: infra.appConfig.bastionEnabled ? infra.vpc.bastion : undefined,
      EngineAddresses: infra.engineAddresses,
      Dashboard: infra.engineAddresses.externalServerUrl,
      DashboardAdminEmail: infra.adminEmail,
      DashboardAdminPassword: infra.adminPassword.value
    }

  },
});
