// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path="./.sst/platform/config.d.ts" />


// TODO: drop eslint config from old nextjs boilerplate
// TODO: better password creation/DATABASE_URL etc secret creation (e.g. from env var, or autogenerated, or from sst secret)
// TODO: don't store secrets in task definition env vars. use secrets instead which get passed in via `ssm` arguments
// TODO: separate service for dashboard? would require a dependency on first service which runs setup-config becoming stable.
// TODO: is SERVER_URL working? seems so.
// TODO: service can be placed into private subnets if desired in the transform which deals with SGs to Broker, but then a NAT gateway is needed (I think) to pull the images from ghcr.io
// TODO: put migrate/setup-config in their own service which gets conditionally deployed to avoid redeployment error on tenant pkey?
// TODO: hatchet-worker in same vpc
// TODO: get it working when no route53 domain provided (bastion helpful here)


export default $config({
  app(input) {
    return {
      name: "hatchet",
      removal: input?.stage === "production" ? "retain" : "remove",
      protect: ["production"].includes(input?.stage),
      home: "aws",
    };
  },
  async run() {
    const infra = await import("./infra/main")

    return {
      Bastion: infra.appConfig.bastionEnabled ? infra.vpc.bastion : undefined,
      EngineAddresses: infra.engineAddresses,
    }

  },
});
